/**
 * Unimeet Service
 * User Api Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: emreecann28@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comment } from './comment';
import { Like } from './like';
import { User } from './user';


export interface Post { 
    comment?: Array<Comment>;
    content?: string;
    like?: Array<Like>;
    postId?: number;
    user?: User;
}
