/**
 * Unimeet Service
 * User Api Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: emreecann28@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserViewDTO } from './userViewDTO';


export interface PostViewDTO { 
    content?: string;
    postId?: number;
    user?: UserViewDTO;
}
