/**
 * Unimeet Service
 * User Api Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: emreecann28@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Department } from './department';
import { University } from './university';
import { User } from './user';


export interface UniDept { 
    departments?: Department;
    uniDeptId?: number;
    universities?: University;
    users?: Array<User>;
}
