/**
 * Unimeet Service
 * User Api Documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: emreecann28@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Comment } from './comment';
import { Like } from './like';
import { UniDept } from './uniDept';


export interface User { 
    comment?: Array<Comment>;
    email?: string;
    firstName?: string;
    gender?: string;
    lastName?: string;
    like?: Array<Like>;
    phoneNumber?: string;
    uniDept?: UniDept;
    userBio?: string;
    userId?: number;
    userName?: string;
    userPassword?: string;
}
