// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSjH2xlkOYWwuU5P-BYTol5FDDYgTQABs',
    appId: '1:652449277539:web:16e19e2e8e823568b53a56',
    messagingSenderId: '652449277539',
    projectId: 'unimeet101',
    authDomain: 'unimeet101.firebaseapp.com',
    storageBucket: 'unimeet101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9-b2RuCtDJbykalHGzFlXbpsOEtyi_4o',
    appId: '1:652449277539:android:a6c418171d011b87b53a56',
    messagingSenderId: '652449277539',
    projectId: 'unimeet101',
    storageBucket: 'unimeet101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTx919psuaBKMg7A5C3LP9CkFqG7JexZE',
    appId: '1:652449277539:ios:9fb157eacd824cb7b53a56',
    messagingSenderId: '652449277539',
    projectId: 'unimeet101',
    storageBucket: 'unimeet101.appspot.com',
    iosClientId:
        '652449277539-2mqhs276lrvfglp10evmf6b9esj6kopv.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimeet101',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTx919psuaBKMg7A5C3LP9CkFqG7JexZE',
    appId: '1:652449277539:ios:9fb157eacd824cb7b53a56',
    messagingSenderId: '652449277539',
    projectId: 'unimeet101',
    storageBucket: 'unimeet101.appspot.com',
    iosClientId:
        '652449277539-2mqhs276lrvfglp10evmf6b9esj6kopv.apps.googleusercontent.com',
    iosBundleId: 'com.example.unimeet101',
  );
}
